[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "biclust_classifier"
version = "0.1.0"
description = ""
license = { file = "LICENSE" }
authors = [
  { name = "Your Name", email = "you@example.com" }
]
readme = "README.md"